### ISSUE TITLE
The color is displayed on the homepage, Leaderboard, Lobby, and in the game

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_client#111]

**Comment by nilshgt** [comment]
https://github.com/sopra-fs24-group-23/sopra24_client/commit/c2dd63acd7fee6881324820aaa35016039c3c0c6
https://github.com/sopra-fs24-group-23/sopra24_server/commit/41e97bb738b99f3639edf1b53014e013f9f85e4e
