### ISSUE TITLE
Answers should have an indicator, showing how many points they were worth

### ISSUE THREAD

**Issue by Dedphish** [sopra-fs24-group-23/sopra24_client#38]

**Comment by nilshgt** [comment]
https://github.com/sopra-fs24-group-23/sopra24_server/commit/50491ea486ff3d9b3cd0579bc949dfced50986a6
https://github.com/sopra-fs24-group-23/sopra24_client/commit/024a9d7a7740c23ebfae9da8ec008df3cbb638bd
https://github.com/sopra-fs24-group-23/sopra24_client/commit/23949329618c613a3d8f426aeaf5916f4640a6db
